#pragma once
#include <thread>
#include <random>
#include <d3d9.h>
#include <dinput.h>
#include <TlHelp32.h>
#include <mciapi.h>
#include <strsafe.h> 
#include <windows.h>
#include <string>
#include <stdio.h>
#include <winternl.h>
#include <array>
#include <Psapi.h>
#include <dwmapi.h>
#include <algorithm>
#include <stdexcept>
#include <iostream>
#include <ctime>
#include <time.h>
#include <sstream>
#include <map>
#include <tuple>
#include <regex>
#include <ProcessSnapshot.h>
#include <filesystem>
#include <fstream>
#include <mutex>
#include <tchar.h>
#include <urlmon.h>
#include <mmstream.h>
#include <chrono>
#include <d3dx9tex.h>
#include <array>
#include <thread>
#include <windows.h>
#include "glow.hpp"
#include "math.hpp"
#include "memory.hpp"
#include "offsets.hpp"
#include "ImGui/imgui.h"
#define IMGUI_DEFINE_MATH_OPERATORS
#include "ImGui/imgui_impl_dx9.h"
#include "ImGui/imgui_internal.h"
#include "ImGui/imgui_impl_win32.h"
#define IMGUI_DEFINE_MATH_OPERATORS
#pragma comment(lib, "d3d9.lib")
#pragma comment(lib, "dwmapi.lib")
